/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "FatFishUI.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, FatFishUIReflection.h) */
#include "FatFishUIReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::FatFishUI::
#define GLOBAL_NAME ::vl_workflow_global::FatFishUI::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::FatFishUI::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_FatFishUI)
	vl_workflow_global::FatFishUI instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS
	FINALIZE_GLOBAL_STORAGE_CLASS
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_FatFishUI)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	FatFishUI& FatFishUI::Instance()
	{
		return Getvl_workflow_global_FatFishUI().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_::__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::presentation::templates::GuiControlTemplate* __vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_::operator()(const ::vl::reflection::description::Value& __vwsn_viewModel_) const
	{
		{
			return static_cast<::vl::presentation::templates::GuiControlTemplate*>(new ::fatfish::ui::FairyWindowTemplate());
		}
	}

	//-------------------------------------------------------------------

	__vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_::__vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_::operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const
	{
		::vl::__vwsn::This(__vwsnthis_0->self)->Close();
	}
}

/***********************************************************************
Class (::fatfish::ui::FairyWindowConstructor)
***********************************************************************/

namespace fatfish
{
	namespace ui
	{
		void FairyWindowConstructor::__vwsn_fatfish_ui_FairyWindow_Initialize(::fatfish::ui::FairyWindow* __vwsn_this_)
		{
			(this->self = __vwsn_this_);
			{
				::vl::__vwsn::This(this->self)->SetClientSize([&](){ ::vl::presentation::Size __vwsn_temp__; __vwsn_temp__.x = static_cast<::vl::vint>(384); __vwsn_temp__.y = static_cast<::vl::vint>(384); return __vwsn_temp__; }());
			}
			{
				::vl::__vwsn::This(this->self)->SetText(::vl::WString::Unmanaged(L"FatFishFairy"));
			}
			{
				::vl::__vwsn::This(this->self)->SetControlTemplate(vl::Func(::vl_workflow_global::__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(this)));
			}
			{
				(this->contextMenu = new ::vl::presentation::controls::GuiToolstripMenu(::vl::presentation::theme::ThemeName::Menu, static_cast<::vl::presentation::controls::GuiControl*>(nullptr)));
				::vl::__vwsn::This(__vwsn_this_)->SetNamedObject(::vl::WString::Unmanaged(L"contextMenu"), ::vl::__vwsn::Box(this->contextMenu));
			}
			{
				(this->themeMenuItem = new ::vl::presentation::controls::GuiToolstripButton(::vl::presentation::theme::ThemeName::MenuItemButton));
				::vl::__vwsn::This(__vwsn_this_)->SetNamedObject(::vl::WString::Unmanaged(L"themeMenuItem"), ::vl::__vwsn::Box(this->themeMenuItem));
			}
			{
				::vl::__vwsn::This(this->themeMenuItem)->SetText(::vl::WString::Unmanaged(L"主题"));
			}
			{
				::vl::__vwsn::This(::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->contextMenu)->GetToolstripItems()).Obj())->Add(::vl::__vwsn::Box(this->themeMenuItem));
			}
			{
				(this->__vwsn_precompile_0 = new ::vl::presentation::controls::GuiToolstripButton(::vl::presentation::theme::ThemeName::MenuItemButton));
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetText(::vl::WString::Unmanaged(L"退出"));
			}
			{
				::vl::__vwsn::This(::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(this->contextMenu)->GetToolstripItems()).Obj())->Add(::vl::__vwsn::Box(this->__vwsn_precompile_0));
			}
			{
				::vl::__vwsn::This(this->self)->AddControlHostComponent(static_cast<::vl::presentation::controls::GuiControlHost*>(this->contextMenu));
			}
			(this->fairyCanvas = new ::vl::presentation::compositions::GuiBoundsComposition());
			::vl::__vwsn::This(__vwsn_this_)->SetNamedObject(::vl::WString::Unmanaged(L"fairyCanvas"), ::vl::__vwsn::Box(this->fairyCanvas));
			{
				::vl::__vwsn::This(this->fairyCanvas)->SetAlignmentToParent([&](){ ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
			}
			(this->fairyImage = ::vl::Ptr<::vl::presentation::elements::GuiImageFrameElement>(::vl::reflection::description::Element_Constructor<::vl::presentation::elements::GuiImageFrameElement>()));
			::vl::__vwsn::This(__vwsn_this_)->SetNamedObject(::vl::WString::Unmanaged(L"fairyImage"), ::vl::__vwsn::Box(this->fairyImage));
			{
				::vl::__vwsn::This(this->fairyImage.Obj())->SetStretch(true);
			}
			{
				::vl::__vwsn::This(this->fairyCanvas)->SetOwnedElement(::vl::Ptr<::vl::presentation::elements::IGuiGraphicsElement>(this->fairyImage));
			}
			{
				::vl::__vwsn::This(::vl::__vwsn::This(this->self)->GetContainerComposition())->AddChild(static_cast<::vl::presentation::compositions::GuiGraphicsComposition*>(this->fairyCanvas));
			}
			{
				auto __vwsn_event_handler_ = vl::Func(::vl_workflow_global::__vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(this));
				::vl::__vwsn::EventAttach(::vl::__vwsn::This(this->__vwsn_precompile_0)->Clicked, __vwsn_event_handler_);
			}
		}

		FairyWindowConstructor::FairyWindowConstructor()
			: self(static_cast<::fatfish::ui::FairyWindow*>(nullptr))
			, contextMenu(static_cast<::vl::presentation::controls::GuiToolstripMenu*>(nullptr))
			, themeMenuItem(static_cast<::vl::presentation::controls::GuiToolstripButton*>(nullptr))
			, fairyCanvas(static_cast<::vl::presentation::compositions::GuiBoundsComposition*>(nullptr))
			, fairyImage(::vl::Ptr<::vl::presentation::elements::GuiImageFrameElement>())
			, __vwsn_precompile_0(static_cast<::vl::presentation::controls::GuiToolstripButton*>(nullptr))
		{
		}

/***********************************************************************
Class (::fatfish::ui::FairyWindow)
***********************************************************************/

		FairyWindow::FairyWindow()
			: ::vl::presentation::controls::GuiWindow(::vl::presentation::theme::ThemeName::Window)
		{
			auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"fatfish::ui::FairyWindow"));
			auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
			::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
			::vl::__vwsn::This(this)->__vwsn_fatfish_ui_FairyWindow_Initialize(this);
		}

		FairyWindow::~FairyWindow()
		{
			this->FinalizeInstanceRecursively(static_cast<::vl::presentation::controls::GuiControlHost*>(this));
		}

/***********************************************************************
Class (::fatfish::ui::FairyWindowTemplateConstructor)
***********************************************************************/

		void FairyWindowTemplateConstructor::__vwsn_fatfish_ui_FairyWindowTemplate_Initialize(::fatfish::ui::FairyWindowTemplate* __vwsn_this_)
		{
			(this->__vwsn_precompile_0 = __vwsn_this_);
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetTitleBarOption(::vl::presentation::BoolOption::AlwaysFalse);
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetIconVisibleOption(::vl::presentation::BoolOption::AlwaysFalse);
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetSizeBoxOption(::vl::presentation::BoolOption::AlwaysFalse);
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetBorderOption(::vl::presentation::BoolOption::AlwaysFalse);
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetMinimizedBoxOption(::vl::presentation::BoolOption::AlwaysFalse);
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetMaximizedBoxOption(::vl::presentation::BoolOption::AlwaysFalse);
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetCustomFramePadding([&](){ ::vl::presentation::Margin __vwsn_temp__; __vwsn_temp__.left = static_cast<::vl::vint>(0); __vwsn_temp__.top = static_cast<::vl::vint>(0); __vwsn_temp__.right = static_cast<::vl::vint>(0); __vwsn_temp__.bottom = static_cast<::vl::vint>(0); return __vwsn_temp__; }());
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetCustomFrameEnabled(true);
			}
			(this->__vwsn_precompile_1 = ::vl::Ptr<::vl::presentation::elements::GuiSolidBackgroundElement>(::vl::reflection::description::Element_Constructor<::vl::presentation::elements::GuiSolidBackgroundElement>()));
			{
				::vl::__vwsn::This(this->__vwsn_precompile_1.Obj())->SetColor(::vl::__vwsn::Parse<::vl::presentation::Color>(::vl::WString::Unmanaged(L"#00FF00")));
			}
			{
				::vl::__vwsn::This(this->__vwsn_precompile_0)->SetOwnedElement(::vl::Ptr<::vl::presentation::elements::IGuiGraphicsElement>(this->__vwsn_precompile_1));
			}
		}

		FairyWindowTemplateConstructor::FairyWindowTemplateConstructor()
			: __vwsn_precompile_0(static_cast<::fatfish::ui::FairyWindowTemplate*>(nullptr))
			, __vwsn_precompile_1(::vl::Ptr<::vl::presentation::elements::GuiSolidBackgroundElement>())
		{
		}

/***********************************************************************
Class (::fatfish::ui::FairyWindowTemplate)
***********************************************************************/

		FairyWindowTemplate::FairyWindowTemplate()
		{
			auto __vwsn_resource_ = ::vl::__vwsn::This(::vl::presentation::GetResourceManager())->GetResourceFromClassName(::vl::WString::Unmanaged(L"fatfish::ui::FairyWindowTemplate"));
			auto __vwsn_resolver_ = ::vl::Ptr<::vl::presentation::GuiResourcePathResolver>(new ::vl::presentation::GuiResourcePathResolver(__vwsn_resource_, ::vl::__vwsn::This(__vwsn_resource_.Obj())->GetWorkingDirectory()));
			::vl::__vwsn::This(this)->SetResourceResolver(__vwsn_resolver_);
			::vl::__vwsn::This(this)->__vwsn_fatfish_ui_FairyWindowTemplate_Initialize(this);
		}

		FairyWindowTemplate::~FairyWindowTemplate()
		{
			this->FinalizeInstanceRecursively(static_cast<::vl::presentation::templates::GuiTemplate*>(this));
		}

	}
}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
