/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_FATFISHUIPARTIALCLASSES
#define VCZH_WORKFLOW_COMPILER_GENERATED_FATFISHUIPARTIALCLASSES

#include "GacUI.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	struct __vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
	struct __vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
	struct __vwsnf3_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
	class __vwsnc1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize__vl_reflection_description_IValueSubscription;
}

namespace fatfish
{
	namespace ui
	{
		class FairyWindowConstructor;
		class FairyWindow;
		class FairyWindowTemplateConstructor;
		class FairyWindowTemplate;

		class FairyWindowConstructor : public ::vl::Object, public ::vl::reflection::Description<FairyWindowConstructor>
		{
			friend class ::vl_workflow_global::__vwsnc1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize__vl_reflection_description_IValueSubscription;
			friend struct ::vl_workflow_global::__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
			friend struct ::vl_workflow_global::__vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
			friend struct ::vl_workflow_global::__vwsnf3_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindowConstructor>;
#endif
		protected:
			::fatfish::ui::FairyWindow* self;
			::vl::presentation::controls::GuiToolstripMenu* contextMenu;
			::vl::presentation::controls::GuiToolstripButton* themeMenuItem;
			::vl::presentation::compositions::GuiBoundsComposition* fairyCanvas;
			::vl::Ptr<::vl::presentation::elements::GuiImageFrameElement> fairyImage;
			::vl::Ptr<::vl::presentation::elements::GuiSolidLabelElement> progressLabel;
			::vl::presentation::controls::GuiToolstripButton* __vwsn_precompile_0;
			::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_1;
			void __vwsn_fatfish_ui_FairyWindow_Initialize(::fatfish::ui::FairyWindow* __vwsn_this_);
		public:
			FairyWindowConstructor();
		};

		class FairyWindow : public ::vl::presentation::controls::GuiWindow, public ::fatfish::ui::FairyWindowConstructor, public ::vl::reflection::Description<FairyWindow>
		{
			friend class ::fatfish::ui::FairyWindowConstructor;
			friend class ::vl_workflow_global::__vwsnc1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize__vl_reflection_description_IValueSubscription;
			friend struct ::vl_workflow_global::__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
			friend struct ::vl_workflow_global::__vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
			friend struct ::vl_workflow_global::__vwsnf3_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindow>;
#endif
		public:
			FairyWindow();
			~FairyWindow();
		};

		class FairyWindowTemplateConstructor : public ::vl::Object, public ::vl::reflection::Description<FairyWindowTemplateConstructor>
		{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindowTemplateConstructor>;
#endif
		protected:
			::fatfish::ui::FairyWindowTemplate* __vwsn_precompile_0;
			::vl::Ptr<::vl::presentation::elements::GuiSolidBackgroundElement> __vwsn_precompile_1;
			void __vwsn_fatfish_ui_FairyWindowTemplate_Initialize(::fatfish::ui::FairyWindowTemplate* __vwsn_this_);
		public:
			FairyWindowTemplateConstructor();
		};

		class FairyWindowTemplate : public ::vl::presentation::templates::GuiWindowTemplate, public ::fatfish::ui::FairyWindowTemplateConstructor, public ::vl::reflection::Description<FairyWindowTemplate>
		{
			friend class ::fatfish::ui::FairyWindowTemplateConstructor;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindowTemplate>;
#endif
		public:
			FairyWindowTemplate();
			~FairyWindowTemplate();
		};

	}
}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class FatFishUI
	{
	public:

		static FatFishUI& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	struct __vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_
	{
		::fatfish::ui::FairyWindowConstructor* __vwsnthis_0;

		__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0);

		::vl::presentation::templates::GuiControlTemplate* operator()(const ::vl::reflection::description::Value& __vwsn_viewModel_) const;
	};

	struct __vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_
	{
		::fatfish::ui::FairyWindowConstructor* __vwsnthis_0;

		__vwsnf2_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};

	struct __vwsnf3_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_
	{
		::fatfish::ui::FairyWindowConstructor* __vwsnthis_0;

		__vwsnf3_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0);

		void operator()(const ::vl::reflection::description::Value& __vwsn_value_) const;
	};

	class __vwsnc1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize__vl_reflection_description_IValueSubscription : public ::vl::Object, public virtual ::vl::reflection::description::IValueSubscription
	{
	public:
		::fatfish::ui::FairyWindowConstructor* __vwsnthis_0;

		__vwsnc1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize__vl_reflection_description_IValueSubscription(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0);

		::fatfish::ui::FairyWindow* __vwsn_bind_cache_0 = nullptr;
		::vl::Ptr<::vl::reflection::description::IEventHandler> __vwsn_bind_handler_0_0;
		bool __vwsn_bind_opened_ = false;
		bool __vwsn_bind_closed_ = false;
		void __vwsn_bind_activator_();
		void __vwsn_bind_callback_0_0(::vl::presentation::compositions::GuiGraphicsComposition* __vwsn_bind_callback_argument_0, ::vl::presentation::compositions::GuiEventArgs* __vwsn_bind_callback_argument_1);
		bool Open() override;
		bool Update() override;
		bool Close() override;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
