/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_FATFISHUIPARTIALCLASSES
#define VCZH_WORKFLOW_COMPILER_GENERATED_FATFISHUIPARTIALCLASSES

#include "GacUI.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	struct __vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
}

namespace fatfish
{
	namespace ui
	{
		class FairyWindowConstructor;
		class FairyWindow;
		class FairyWindowTemplateConstructor;
		class FairyWindowTemplate;

		class FairyWindowConstructor : public ::vl::Object, public ::vl::reflection::Description<FairyWindowConstructor>
		{
			friend struct ::vl_workflow_global::__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindowConstructor>;
#endif
		protected:
			::vl::presentation::compositions::GuiBoundsComposition* fairyCanvas;
			::vl::Ptr<::vl::presentation::elements::GuiImageFrameElement> fairyImage;
			::fatfish::ui::FairyWindow* __vwsn_precompile_0;
			void __vwsn_fatfish_ui_FairyWindow_Initialize(::fatfish::ui::FairyWindow* __vwsn_this_);
		public:
			FairyWindowConstructor();
		};

		class FairyWindow : public ::vl::presentation::controls::GuiWindow, public ::fatfish::ui::FairyWindowConstructor, public ::vl::reflection::Description<FairyWindow>
		{
			friend class ::fatfish::ui::FairyWindowConstructor;
			friend struct ::vl_workflow_global::__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindow>;
#endif
		public:
			FairyWindow();
			~FairyWindow();
		};

		class FairyWindowTemplateConstructor : public ::vl::Object, public ::vl::reflection::Description<FairyWindowTemplateConstructor>
		{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindowTemplateConstructor>;
#endif
		protected:
			::fatfish::ui::FairyWindowTemplate* __vwsn_precompile_0;
			::vl::Ptr<::vl::presentation::elements::GuiSolidBackgroundElement> __vwsn_precompile_1;
			void __vwsn_fatfish_ui_FairyWindowTemplate_Initialize(::fatfish::ui::FairyWindowTemplate* __vwsn_this_);
		public:
			FairyWindowTemplateConstructor();
		};

		class FairyWindowTemplate : public ::vl::presentation::templates::GuiWindowTemplate, public ::fatfish::ui::FairyWindowTemplateConstructor, public ::vl::reflection::Description<FairyWindowTemplate>
		{
			friend class ::fatfish::ui::FairyWindowTemplateConstructor;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<FairyWindowTemplate>;
#endif
		public:
			FairyWindowTemplate();
			~FairyWindowTemplate();
		};

	}
}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class FatFishUI
	{
	public:

		static FatFishUI& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	struct __vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_
	{
		::fatfish::ui::FairyWindowConstructor* __vwsnthis_0;

		__vwsnf1_FatFishUI_fatfish_ui_FairyWindowConstructor___vwsn_fatfish_ui_FairyWindow_Initialize_(::fatfish::ui::FairyWindowConstructor* __vwsnctorthis_0);

		::vl::presentation::templates::GuiControlTemplate* operator()(const ::vl::reflection::description::Value& __vwsn_viewModel_) const;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
