/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "FatFishUIReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(fatfish::ui::FairyWindow)
			IMPL_CPP_TYPE_INFO(fatfish::ui::FairyWindowConstructor)
			IMPL_CPP_TYPE_INFO(fatfish::ui::FairyWindowTemplate)
			IMPL_CPP_TYPE_INFO(fatfish::ui::FairyWindowTemplateConstructor)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_CLASS_MEMBER(::fatfish::ui::FairyWindow)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_cpp_Friend, ::vl::reflection::description::GetTypeDescriptor(::vl::WString::Unmanaged(L"fatfish::ui::FairyWindowConstructor")))
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::fatfish::ui::FairyWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::fatfish::ui::FairyWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(::fatfish::ui::FairyWindow)

			BEGIN_CLASS_MEMBER(::fatfish::ui::FairyWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::fatfish::ui::FairyWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_fatfish_ui_FairyWindow_Initialize, { L"__vwsn_this_" })
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(contextMenu)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(fairyCanvas)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(fairyImage)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(self)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(themeMenuItem)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
			END_CLASS_MEMBER(::fatfish::ui::FairyWindowConstructor)

			BEGIN_CLASS_MEMBER(::fatfish::ui::FairyWindowTemplate)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_cpp_Friend, ::vl::reflection::description::GetTypeDescriptor(::vl::WString::Unmanaged(L"fatfish::ui::FairyWindowTemplateConstructor")))
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiWindowTemplate)
				CLASS_MEMBER_BASE(::fatfish::ui::FairyWindowTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::fatfish::ui::FairyWindowTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(::fatfish::ui::FairyWindowTemplate)

			BEGIN_CLASS_MEMBER(::fatfish::ui::FairyWindowTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::fatfish::ui::FairyWindowTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_fatfish_ui_FairyWindowTemplate_Initialize, { L"__vwsn_this_" })
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
			END_CLASS_MEMBER(::fatfish::ui::FairyWindowTemplateConstructor)

#undef _
			class FatFishUITypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::fatfish::ui::FairyWindow)
					ADD_TYPE_INFO(::fatfish::ui::FairyWindowConstructor)
					ADD_TYPE_INFO(::fatfish::ui::FairyWindowTemplate)
					ADD_TYPE_INFO(::fatfish::ui::FairyWindowTemplateConstructor)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadFatFishUITypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new FatFishUITypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
